name: archiveFiles
on:
  workflow_dispatch:
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Zip files
      run: 7z u ${{ runner.temp }}/${{ github.run_id }}.zip ${{ github.workspace }}/hello_world
    - name: Tar files
      run: tar -czf ${{ runner.temp }}/${{ github.run_id }}.zip ${{ github.workspace }} --overwrite
