name: jdunham-infomagnus/azure_key_vault
on:
  workflow_dispatch:
jobs:
  azure1:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "${{ secrets.AZURE_KEYVAULT }}"
        secrets: my-secret
      id: azure_keyvault
    - name: set my-secret
      run: export my-secret="32"
    - name: set secret envs
      shell: bash
      run: echo 'MY_SECRET=$my-secret' >> $GITHUB_ENV
    - name: checkout
      uses: actions/checkout@v2
    - name: echo message
      run: echo Found $MY_SECRET
