# This is a basic workflow to help you get started with Actions

name: azure_key_vault

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        id: set_env
        run: | 
          export AZ_ENV='yellow'
          echo "TEST=$AZ_ENV" >> $GITHUB_ENV
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $TEST
          
