name: jdunham-infomagnus/azure_key_vault
on:
  workflow_dispatch:
jobs:
  azure:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: https://valetkvjd.vault.azure.net/
        secrets: TEST
      id: azure_keyvault
    - name: set job envs
      shell: bash
      run: echo 'MY_SECRET=${{ steps.azure_keyvault.outputs.TEST }}' >> $GITHUB_ENV
    - name: checkout
      uses: actions/checkout@v2
    - name: sh
      shell: bash
      run: '"echo $MY_SECRET"'
