name: jdunham-infomagnus/cifs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: transfer files over CIFS
      run: |-
        sudo mkdir -p /mnt/cifs_share
        sudo mount -t cifs -o username=${{ env.JD_USER }},password=${{ secrets.JD_PASSWORD }} //${{ env.JD_HOST }}/${{ env.JD_SHARE_DIR }} /mnt/cifs_share
        sudo rsync -a --prune-empty-dirs --exclude='**/test/**' --exclude='**/*~' --exclude='**/#*#' --exclude='**/.#*' --exclude='**/%*%' --exclude='**/._*' --exclude='**/CVS' --exclude='**/CVS/**' --exclude='**/.cvsignore' --exclude='**/SCCS' --exclude='**/SCCS/**' --exclude='**/vssver.scc' --exclude='**/.svn' --exclude='**/.svn/**' --exclude='**/.DS_Store' --exclude='**/.git' --exclude='**/.git/**' --exclude='**/.gitattributes' --exclude='**/.gitignore' --exclude='**/.gitmodules' --exclude='**/.hg' --exclude='**/.hg/**' --exclude='**/.hgignore' --exclude='**/.hgsub' --exclude='**/.hgsubstate' --exclude='**/.hgtags' --exclude='**/.bzr' --exclude='**/.bzr/**' --exclude='**/.bzrignore' --include='**/*.txt' --include='*/' --exclude='*' ./ /mnt/cifs_share/
        sudo umount /mnt/cifs_share
      env:
        JD_SHARE_DIR: cifs_share
        JD_HOST: 18.207.220.55
        JD_USER: jenkins
    - name: transfer files over CIFS
      run: |-
        sudo mkdir -p /mnt/cifs_share
        sudo mount -t cifs -o username=${{ env.JD_USER }},password=${{ secrets.JD_PASSWORD }} //${{ env.JD_HOST }}/${{ env.JD_SHARE_DIR }} /mnt/cifs_share
        sudo rsync -a --prune-empty-dirs --exclude='**/*~' --exclude='**/#*#' --exclude='**/.#*' --exclude='**/%*%' --exclude='**/._*' --exclude='**/CVS' --exclude='**/CVS/**' --exclude='**/.cvsignore' --exclude='**/SCCS' --exclude='**/SCCS/**' --exclude='**/vssver.scc' --exclude='**/.svn' --exclude='**/.svn/**' --exclude='**/.DS_Store' --exclude='**/.git' --exclude='**/.git/**' --exclude='**/.gitattributes' --exclude='**/.gitignore' --exclude='**/.gitmodules' --exclude='**/.hg' --exclude='**/.hg/**' --exclude='**/.hgignore' --exclude='**/.hgsub' --exclude='**/.hgsubstate' --exclude='**/.hgtags' --exclude='**/.bzr' --exclude='**/.bzr/**' --exclude='**/.bzrignore' --include='**/test/**' --include='*/' --exclude='*' ./ /mnt/cifs_share/
        sudo umount /mnt/cifs_share
      env:
        JD_SHARE_DIR: cifs_share
        JD_HOST: 18.207.220.55
        JD_USER: jenkins
    - name: transfer files over CIFS
      run: |-
        sudo mkdir -p /mnt/cifs_share
        sudo mount -t cifs -o username=${{ env.JD_USER }},password=${{ secrets.JD_PASSWORD }} //${{ env.JD_HOST }}/${{ env.JD_SHARE_DIR }} /mnt/cifs_share
        sudo mkdir -p /mnt/cifs_share/foo
        sudo rsync -a --prune-empty-dirs --exclude='**/*~' --exclude='**/#*#' --exclude='**/.#*' --exclude='**/%*%' --exclude='**/._*' --exclude='**/CVS' --exclude='**/CVS/**' --exclude='**/.cvsignore' --exclude='**/SCCS' --exclude='**/SCCS/**' --exclude='**/vssver.scc' --exclude='**/.svn' --exclude='**/.svn/**' --exclude='**/.DS_Store' --exclude='**/.git' --exclude='**/.git/**' --exclude='**/.gitattributes' --exclude='**/.gitignore' --exclude='**/.gitmodules' --exclude='**/.hg' --exclude='**/.hg/**' --exclude='**/.hgignore' --exclude='**/.hgsub' --exclude='**/.hgsubstate' --exclude='**/.hgtags' --exclude='**/.bzr' --exclude='**/.bzr/**' --exclude='**/.bzrignore' --include='**/*.txt' --include='*/' --exclude='*' ./ /mnt/cifs_share/foo
        sudo umount /mnt/cifs_share
      env:
        JD_SHARE_DIR: cifs_share
        JD_HOST: 18.207.220.55
        JD_USER: jenkins
      if: always()
