name: jdunham-infomagnus/cifs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: echo "testing" >> server1_test.txt
    - name: transfer files over CIFS
      run: |-
        sudo mkdir /mnt/cifs_share
        sudo mount -t cifs -o username=jenkins,password=ruby!sC00l //3.237.197.235/${{ env.JD_SHARE_DIR }} /mnt/cifs_share
        sudo mkdir -p /mnt/cifs_share/
        sudo rsync -a --include='*/' --include='**/*.txt' --exclude='*' --exclude='**/.git/** ' --exclude='.github' ./ /mnt/cifs_share/
      env:
        JD_SHARE_DIR: cifs_share
