# This is a basic workflow to help you get started with Actions

name: CIFS

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir /mnt/test
          chmod 777 /mnt/test
          mount -t cifs -o user=jenkins,password=ruby!sC00l //3.237.197.235/cifs_share /mnt/test/
          cd /mnt/test
          sudo touch github.txt
          ls
