name: Project CI
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
on: [push, pull_request, workflow_dispatch]
jobs:
  test_ui:
    defaults:
      run:
        working-directory: ./ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
