name: jdunham-infomagnus/copy_artifact_designer
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: clean workspace
      shell: bash
      run: rm -rf ${{ github.workspace }}/*
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: mkdir -p results
    - name: download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        workflow: "${{ env.WORKFLOW_NAME }}"
        run_id: "${{ env.RUN_ID }}"
        name: "${{ env.ARTIFACT_NAME }}"
        path: "${{ env.TARGET_PATH }}"
        repo: "${{ env.REPO }}"
      env:
        WORKFLOW_NAME: test_upload.yml
        TARGET_PATH: results
        ARTIFACT_NAME: my-artifact
        REPO: "${{github.repository}}"
        RUN_ID: 939744222
      continue-on-error: false
    - name: run command
      shell: bash
      run: tree
