name: build-playground/SqlAzureDacpacDeployment
on:
  workflow_dispatch:
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Create Inline SQL File
      run: |-
        @'
        INSERT INTO dbo.BuildVersion ([Database Version], VersionDate) VALUES (1, CURRENT_TIMESTAMP)
        INSERT INTO dbo.BuildVersion ([Database Version], VersionDate) VALUES (1, CURRENT_TIMESTAMP)
        '@ | Add-Content ${{ runner.TEMP }}\dacpac_deploy.sq
    - run: cat ${{ runner.TEMP }}\dacpac_deploy.sq
    # if Allow Azure Services and resources to access this server are ON the Azure/login step above can likely be removed
#     - name: Azure SQL Deploy
#       uses: Azure/sql-action@v1
#       with:
#         server-name: "${{ env.SERVER_NAME }}"
#         connection-string: "${{ secrets.DACPAC_CONNECTION  }}"
#         sql-file: "${{ runner.TEMP }}\dacpac_deploy.sql"
#       env:
#         SERVER_NAME: jd-testing.database.windows.net

