name: valet-dev-testing/circle-demo/build
on:
  push:
jobs:
  docker-test:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:trusty
    steps:
    - run: |-
        curl -O --silent --show-error --location --fail --retry 3 \
        https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
