name: docker-build-publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: docker.io/dunhamj/hello-world
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: docker.io/dunhamj/hello-world:latest
