name: jdunham-infomagnus/file_download
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: create folder
      shell: bash
      run: mkdir -p downloads
    - name: download file
      shell: bash
      run: curl https://www.digitalocean.com/robots.txt --output downloads/test.txt
    - name: post mortem
      shell: bash
      run: cat downloads/test.txt
