name: jdunham-infomagnus/file_download
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: create folder
      shell: bash
      run: mkdir -p downloads
    - name: download file
      shell: bash
      run: curl https://www.digitalocean.com/robots.txt --user matz:${{ secrets.FILE_DOWNLOAD_PASSWORD }} --output downloads/test.txt
    - name: run command
      shell: bash
      run: cat downloads/test.txt

      shell: bash
      run: 7z a archive/${{ github.job }}.zip .//*
    - name: post mortem
      shell: bash
      run: |- 
        cat downloads/test.txt
        ls archive 
