# This is a basic workflow to help you get started with Actions

name: extract-files-validation

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
        
  ubuntu_validation_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install execa
      - name: Extract Files
        uses: actions/github-script@v4
        env:
         DESTINATION_FOLDER: base_folder
         FILE_PATTERNS: "**/*.zip"
       
        with:
         script: |         
            const fs = require('fs').promises
            const path = require('path')
            const execa = require('execa')
            const target = path.resolve(process.env.DESTINATION_FOLDER)
            const patterns = process.env.FILE_PATTERNS
            
            const { stdout } = await execa('echo', ['hello', 'world'])

            console.log(stdout)
