
name: node_exec

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install execa
      - uses: actions/github-script@v4
        with:
          script: |
            const execa = require('execa')

            const { stdout } = await execa('echo "hello world"')

            console.log(stdout)
