name: jdunham-infomagnus/file_designer
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: create file
      shell: bash
      run: |-
        echo 'Hello world!
        blah
        blah
        faslkdfj' > created.txt
    - uses: actions/github-script@v3
      env:
        TARGET_LOCATION: "./new"
        FILE_PATTERNS: "**/**.yml,**/**.txt,!**/**.js"
      with:
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const target = path.resolve(process.env.TARGET_LOCATION)
          const patterns = process.env.FILE_PATTERNS
          const globber = await glob.create(patterns.replace(",", "\n"))
          for await (const file of globber.globGenerator()) {
            if ((await fs.lstat(file)).isDirectory()) continue
            const dest = path.join(target, file.substring(process.cwd().length))
            await io.mkdirP(path.dirname(dest))
            await io.cp(file, dest)
          }
    - name: test before
      shell: bash
      run: |-
        ls -la new
        ls -la new/.github/actions/cat-facts
    - uses: actions/github-script@v3
      env:
        FILE_PATTERNS: "**/**.txt,!**/**.yaml"
      with:
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const patterns = process.env.FILE_PATTERNS
          const globber = await glob.create(patterns.replace(",", "\n"))
          for await (const file of globber.globGenerator()) {
            if ((await fs.lstat(file)).isDirectory()) continue
            await io.rmRF(file)
          }
    - name: test after
      shell: bash
      run: |-
        ls -la new
        ls -la new/.github/actions/cat-facts
