name: PublishOverFTP
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: |-
        echo "${{ github.workflow }}-${{ github.run_id }}" > job.txt
        echo "It Worked!!" > new1.txt
        mkdir -p new/test
        echo "{}" > new/test/bar.json
        ls new/test
    - name: setup ftp transfer file
      uses: actions/github-script@v3
      with:
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const patterns = "new1.txt"
          const globber = await glob.create(patterns.replace(",", "\n"))
          const files = []
          const dirs = []
          const exludes = ['./', '.\']
          for await (let file of globber.globGenerator()) {
            file = path.relative(process.cwd(), file)
            if ((await fs.lstat(file)).isDirectory()) continue
              path.dirname(file).split(path.sep).reduce((prevPath, folder) => {
              const currentPath = path.join(prevPath, folder, path.sep);
              if (!exludes.includes(currentPath)) {
                dirs.push("mkdir " + currentPath);
              }
              return currentPath;
            }, '');
            files.push("put " + file)
          }
          uniq_dirs = [...new Set(dirs)];
          uniq_dirs.sort((a, b) => {
            return a.length - b.length;
          });
          var results = [
            "open ${{ secrets.JD_FTP_SERVER_HOST }} 21",
            "user ${{ secrets.JD_FTP_SERVER_USER }} ${{ secrets.JD_FTP_SERVER_PASSWORD }}",
            "cd ${{ env.REMOTE_DIRECTORY }}"
          ]
          results = result.concat(uniq_dirs.concat(files))
          fs.writeFile("JD_FTP_SERVER_transfer.txt", results.join("\n"), (err) => { })
      env:
        REMOTE_DIRECTORY: UPDATE_ME
    - name: run file transfers
      run: ftp -pvn < JD_FTP_SERVER_transfer.txt
