name: build-playground/gatesTesting
on:
  workflow_dispatch:
jobs:
  Dev:
    runs-on: macos-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
    - name: 'Gate Test'
      shell: bash
      run: |-
        curl -f -X "POST" https://httpbin.org/post \
        -H Content-Type:application/json \
        | jq -e '${{env.SUCCESS_CRITERIA }}'
      env:
        SUCCESS_CRITERIA: '.url == "https://httpbin.org/post"'
    - name: Bash Script
      run: |-
        # Write your commands here
        echo 'Hello world'
      shell: bash
