# This is a basic workflow to help you get started with Actions

name: github_script_prac

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set envs
        uses: actions/github-script@v4
        env:
          PROPERTIES_PATH: ./env.properties
        with:
         script: |
          const fs = require("fs")
          fs.readFile(process.env.PROPERTIES_PATH, 'utf8', (err, data) => {
            if (err) throw err;
            const lines = data
              // joins multiline properties
              .replace(/\\\n( )*/g, '')
              .split('\n')
              // removes comments and empty lines
              .filter(line => line && !line.startsWith("#") && !line.startsWith("!"))

            lines.forEach(line => {
              env = line.match(/(?<key>\w+)\s*?[=:]\s*?(?<value>\S.+)/).groups
              core.exportVariable(env['key'],env['value']);
            })
          });
      - run: printenv
