# This is a basic workflow to help you get started with Actions

name: github_script_prac

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set envs
        uses: actions/github-script@v4    
        with:
         script: |
          core.exportVariable('FOO', 'ItWorked');
          core.notice('Something happened that you might want to know about.')
      - run: printenv
