# This is a basic workflow to help you get started with Actions

name: github_script_prac

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set envs
        uses: actions/github-script@v4    
        with:
         script: |
          let val = "ItWorked"
          core.exportVariable('FOO', val);
          core.setSecret(val);
          core.info(`Set 'Foo' to ${val}...`)
      - run: printenv
