# This is a basic workflow to help you get started with Actions

name: github_script_prac

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
        
  ubuntu_validation_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set envs
        uses: actions/github-script@v4    
        with:
         script: |
          const core = require('@actions/core');
          core.exportVariable('FOO', 'ItWorked');

      - run: printenv
