name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: '3.6.3'
      id: install
    - continue-on-error: true
      uses: azure/aks-set-context@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
        resource-group: myResourceGroup
        cluster-name: myAKSCluster
    - shell: bash
      run: |-
        export HELM_EXPERIMENTAL_OCI=1
        version=$(helm chart save ./hello_world jdtesting.azurecr.io/helm/ado_hello_world | grep ref | cut -d : -f3)
        helm registry login jdtesting.azurecr.io --username ${{ secrets.ACR_USER_NAME }} --password ${{ secrets.ACR_PASSWORD }}
        helm chart push jdtesting.azurecr.io/helm/ado_hello_world:$version
        helm chart list
        helm chart remove jdtesting.azurecr.io/helm/ado_hello_world:$version
        helm chart list
