name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # This item has no matching transformer
#     - task: HelmInstaller@0
#       inputs:
#         helmVersion: 3.6.3
#         checkLatestHelmVersion: false
#         installKubectl: true
    - continue-on-error: true
      uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: "${{ secrets.K8S_URL }}"
        k8s-secret: "${{ secrets.K8S_SECRET }}"
    - continue-on-error: true
      shell: bash
      run: helm create --namespace default myCharts
    - run: helm repo add bitnami https://charts.bitnami.com/bitnami
    - continue-on-error: true
      shell: bash
      run: |
        if  helm version --client --short | grep -q "v3"; then
          helm install --namespace default --values values.yml --set key1=val1,key2=val2 --dependency-update mysql bitnami/mysql --version 8.8.11
        else
          helm install --namespace default --values values.yml --set key1=val1,key2=val2 --dependency-update --name mysql --wait --dry-run bitnami/mysql --version 8.8.11
        fi
    - continue-on-error: true
      shell: bash
      run: helm ls
    - continue-on-error: true
      shell: bash
      run: helm get --namespace default all mysql
    - continue-on-error: true
      shell: bash
      run: helm rollback --namespace default mysql
    - continue-on-error: true
      shell: bash
      run: helm uninstall --namespace default mysql
