name: helm_install

on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: latest
    - uses: azure/setup-kubectl@v1
      with:
        version: latest
    - uses: azure/setup-helm@v1
      with:
        version: v2.14.1
    - uses: azure/setup-kubectl@v1
      with:
        version: v1.9.0
    - uses: azure/setup-helm@v1
      with:
        version: latest
    - uses: azure/setup-helm@v1
      with:
        version: latest
    - uses: azure/setup-helm@v1
      with:
        version: v3.6.11
