name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: '3.6.3'
      id: install
    - shell: bash
      run: |-
        export HELM_EXPERIMENTAL_OCI=1
        version=$(helm chart save ./hello_world jdtesting.azurecr.io/helm/ado_hello_world | grep ref | cut -d : -f3)
       
        echo "jdtesting.azurecr.io/helm/ado_hello_world:$version"
