name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: '3.6.3'
      id: install
    - continue-on-error: true
      uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: "${{ secrets.K8S_URL }}"
        k8s-secret: "${{ secrets.K8S_SECRET }}"
    - run: helm repo add bitnami https://charts.bitnami.com/bitnami
    - continue-on-error: true
      shell: bash
      run: |-
        export HELM_EXPERIMENTAL_OCI=1
        helm chart save ./hello-world jdtesting.azurecr.io/helm/ado_hello_world
        helm registry login jdtesting.azurecr.io --username ${{ secrets.ACR_USER_NAME }} --password ${{ secrets.ACR_PASSWORD }}
        helm chart push jdtesting.azurecr.io/helm/hello-world:${{ env.CHART_VERSION }}
      env:
        CHART_VERSION: 0.1.2
