name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: "${{ secrets.K8S_URL }}"
        k8s-secret: "${{ secrets.K8S_SECRET }}"
    - continue-on-error: true
      shell: bash
      run: helm create --namespace default myCharts
    - run: ls
