name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: '2.16.12'
      id: install
    - continue-on-error: true
      shell: bash
      run: |
        if  helm version --client --short | grep -q "v3"; then
          echo "version 3"
        else
          echo "version 2"
        fi
    - continue-on-error: true
      shell: bash
      run: helm ls --namespace default
    - continue-on-error: true
      shell: bash
      run: helm delete --namespace default mysql
