name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # This item has no matching transformer
#     - task: HelmInstaller@0
#       inputs:
#         helmVersion: 3.6.3
#         checkLatestHelmVersion: false
#         installKubectl: true
    - continue-on-error: true
      uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: "${{ secrets.K8S_URL }}"
        k8s-secret: "${{ secrets.K8S_SECRET }}"
    - continue-on-error: true
      shell: bash
      run: helm create --namespace default myCharts
    - run: helm repo add bitnami https://charts.bitnami.com/bitnami
    - continue-on-error: true
      shell: bash
      run: |
        if  helm version --client --short | grep -q "v3"; then
          helm install --namespace default --values values.yml --set key1=val1,key2=val2 --dependency-update mysql bitnami/mysql --version 8.8.11
        else
          helm install --namespace default --values values.yml --set key1=val1,key2=val2 --dependency-update --name mysql --wait --dry-run bitnami/mysql --version 8.8.11
        fi
    - continue-on-error: true
      shell: bash
      run: helm ls
    - continue-on-error: true
      shell: bash
      run: helm get --namespace default all mysql
    - continue-on-error: true
      shell: bash
      run: helm delete --namespace default mysql
    - continue-on-error: true
      shell: bash
      run: helm rollback --namespace default mysql
    - continue-on-error: true
      shell: bash
      run: helm uninstall --namespace default mysql
    - continue-on-error: true
      shell: bash
      run: helm package --version 1.2.4 --destination . ./helm_test/hello_world
    - continue-on-error: true
      shell: bash
      run: |
        if  helm version --client --short | grep -q "v3"; then
          helm package --dependency-update --version 1.3.2 --destination . -a yes ./hello-world
        else
          helm package --dependency-update --save --version 1.3.2 --destination . -a yes ./hello-world
        fi
    - continue-on-error: true
      shell: bash
      run: helm upgrade --namespace default --install --recreate-pods --reset-values --force --values values.yml --set key1=val1 --wait --dry-run mysql bitnami/mysql --version 8.8.12
    - continue-on-error: true
      shell: bash
      run: helm upgrade --namespace default --install --recreate-pods --reset-values --force --values values.yml --set key1=val1 --wait --dry-run myRelease ./redis --version 0.2.0
    - continue-on-error: true
      shell: bash
      run: |-
        export HELM_EXPERIMENTAL_OCI=1
        helm chart save ./helm_test/hello-world jdtesting.azurecr.io/helm/ado_hello_world
        helm registry login jdtesting.azurecr.io --username ${{ secrets.ACR_USER_NAME }} --password ${{ secrets.ACR_PASSWORD }}
        helm chart push jdtesting.azurecr.io/helm/ado_hello_world:${{ env.CHART_VERSION }}
      env:
        CHART_VERSION: UPDATE_ME
    - continue-on-error: true
      shell: bash
      run: helm expose --namespace default --dry-run
    - continue-on-error: true
      shell: bash
      run: helm init --canary-image --upgrade --wait --dry-run
