name: helm
on:
  workflow_dispatch:
env:
  System_Debug: 'true'
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      with:
        version: '2.16.12'
      id: install
    - continue-on-error: true
      uses: azure/aks-set-context@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
        resource-group: myResourceGroup
        cluster-name: myAKSCluster
    - run: helm repo add bitnami https://charts.bitnami.com/bitnami
    - continue-on-error: true
      shell: bash
      run: |
        if  helm version --client --short | grep -q "v3"; then
          helm install --namespace default --values values.yml --set key1=val1,key2=val2 --dependency-update mysql bitnami/mysql --version 8.8.11
        else
          helm install --namespace default --values values.yml --set key1=val1,key2=val2 --dependency-update --name mysql bitnami/mysql --version 8.8.11
        fi
    - continue-on-error: true
      shell: bash
      run: helm ls --namespace default
    - continue-on-error: true
      shell: bash
      run: helm delete --namespace default mysql
