name: valet-dev-testing/circle-demo/heroku_deploy
on:
  push:
jobs:
  example:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |-
        if [[ $(command -v heroku) == "" ]]; then
          curl https://cli-assets.heroku.com/install.sh | sh
        else
          echo "Heroku is already installed. No operation was performed."
        fi
    - shell: bash
      run: |-
        heroku container:login
        heroku container:release -a tranquil-springs-41774 web
      timeout-minutes: 10
