name: heroku
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v2
    - run: |-
        if [[ $(command -v heroku) == "" ]]; then
          curl https://cli-assets.heroku.com/install.sh | sh
        else
          echo "Heroku is already installed. No operation was performed."
        fi
    - run: which heroku
