name: heroku
on:
  push:
jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: cimg/base:stable
      options: "--user root"
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        PRINT_WHOAMI: false
        HEROKU_API_KEY: 123
      run: |-
        if [[ $HEROKU_API_KEY == "" ]]; then
          echo "No Heroku API key set, please set the HEROKU_API_KEY environment variable."
          echo "This can be found by running the `heroku auth:token` command locally."
          exit 1
        else
          echo "Heroku API key found."
          if [[ $PRINT_WHOAMI == "true" ]]; then heroku auth:whoami; fi
        fi
    - run: which heroku
