name: jdunham-infomagnus/env_inject
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: echo "ruby=true" > inject.properties
    - name: create env properties file
      shell: bash
      run: |-
        cat > tmp.properties <<'EOL'
        new_path=c:\\wiki\\new
        # my_path=c:\wiki\templates
        key99 = true
        key100 = $key99
        EOL
    - name: inject envs
      uses: actions/github-script@v4
      env:
        PROPERTIES_FILES: tmp.properties,env.properties
      with:
        script: |-
          const fs = require("fs")
          const files = process.env.PROPERTIES_FILES.split(",")
          files.forEach( file => {
            fs.readFile(file, 'utf8', (err, data) => {
              const lines = data
                // joins multiline properties
                .replace(/\\\n( )*/g, '')
                .split('\n')
                // removes comments and empty lines
                .filter(line => line && !line.startsWith("#") && !line.startsWith("!"))
              lines.forEach(line => {
                env = line.match(/(?<key>\w+)\s*?[=:]\s*?(?<value>\S.+)/).groups
                core.exportVariable(env['key'],env['value']);
              })
            })
          core.exportVariable("test1","123");
          core.exportVariable("test2","$test1");
          });
    - name: run command
      shell: bash
      run: | 
        printenv > envs.txt
        echo $test2
