name: jdunham-infomagnus/env_inject
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: printenv > envs.txt
    - name: inject envs
      uses: actions/github-script@v4
      env:
        PROPERTIES_PATH: env.properties
      with:
        script: |
          const fs = require("fs")
          fs.readFile(process.env.PROPERTIES_PATH, 'utf8', (err, data) => {
            const lines = data
              // joins multiline properties
              .replace(/\
          ( )*/g, '')
              .split('
          ')
              // removes comments and empty lines
              .filter(line => line && !line.startsWith("#") && !line.startsWith("!"))
            lines.forEach(line => {
              env = line.match(/(?<key>w+) *?[=:] *?(?<value>S.+)/).groups
              core.exportVariable(env['key'],env['value']);
            })
          });
