name: jdunham-infomagnus/env_inject
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: create properties file
      shell: bash
      run: |-
        cat > inject.properties <<'EOL'
        RUBY=true
        EOL
    - name: create env properties file
      shell: bash
      run: |-
        cat > inject-env.properties <<'EOL'
        # this is a comment
        MY_USER=matz
        MY_HOME:/home/usr/matz
        EOL
    - name: inject property file envs
      uses: actions/github-script@v4
      env:
        PROPERTIES_FILES: "inject-env.properties,inject.properties"
      with:
        script: |-
          const fs = require("fs")
          const files = process.env.PROPERTIES_FILES.split(",")
          files.forEach(file => {
          let envs = {}
          fs.readFile(file, 'utf8', (err, data) => {
            const lines = data
              // joins multiline properties
              .replace(/\\\n( )*/g, '')
              .split('\n')
              // removes comments and empty lines
              .filter(line => line && !line.startsWith("#") && !line.startsWith("!"))
            lines.forEach(line => {
              match = line.match(/(?<key>\w+)\s*?[=:]\s*?(?<value>\S.+)/).groups
              envs[match["key"]] = match["value"]
            })
            for (let [key, value] of Object.entries(envs)) {
              if (value.startsWith("$")) {
                const env_name = value.substring(1)
                if (env_name in process.env) {
                  value = process.env[env_name]
                } else if (env_name in envs) {
                  value = envs[env_name]
                }
              }
              core.exportVariable(key, value);
            }
            })
          });
    - name: read envs
      shell: bash
      run: |-
        echo ${{ env.is_test }}
        echo ${{ env.var1 }}
