name: build-playground/DeploymentGroupFun
on:
  workflow_dispatch:
jobs:
  Stage-1-job-1:
    runs-on: windows-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    strategy:
      max-parallel: 2
      fail-fast: false
    steps:
    - name: Bash Script
      run: |-
        # Write your commands here
        echo 'Hello From Agent Job!'
      shell: bash
  Stage-1-deployment-job-2:
    needs:
    - Stage-1-job-1
    runs-on: ${{ matrix.agent }}
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    timeout-minutes: 10
    strategy:
      max-parallel: 1
      matrix:
        agent:
        - macos-latest
        - ubuntu-latest
    steps:
    - name: Bash Script
      run: |-
        # Write your commands here
        echo 'Hello from Deployment Group Job!'
      shell: bash
