
name: Package Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2
      - name: package?
        run: |
          which rsync
          which ssh
