
name: Package Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: package?
        run: |
          which sshpass
          which ssh
          which scp
          which sftp
