
name: Package Tests

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: package?
        run: |
          which cp
          which mv
          which mkdir
          which unzip
          which echo
          which tar
          which curl
          which zip

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: package?
        run: |
          which cp
          which mv
          which mkdir
          which unzip
          which echo
          which tar
          which zip
          which curl
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: package?
        run: |
          which cp
          which mv
          which mkdir
          which unzip
          which echo
          which tar
          which zip
          which curl
