
name: Package Tests

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: package?
        shell: bash
        run: |
          which jq


  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: package?
        run: |
          which jq

          
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: package?
        run: |
          which jq

