name: jdunham-infomagnus/post_build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install groovy
      shell: bash
      run: |-
        brew install groovy
        groovy -version
        which groovy
    - name: run command
      shell: bash
      run: |-
        # Create generic script
        cat > my_script << 'EOL'
        #!/usr/bin/python
        print("** Running my script on failure..")
        EOL
        # Create groovey script
        cat > my_groovy.groovy << 'EOL'
        println "** Running my groovy script on success!"
        EOL
    - name: run script file
      shell: bash
      run: "./my_script"
      if: "${{ failure() }}"
    - name: run script file
      shell: bash
      run: groovy ./my_groovy.groovy
      if: "${{ success() }}"
    - name: run groovy script
      shell: groovy {0}
      run: |-
        println "** This is my added groovy script"
        println "which runs on success!"
      if: "${{ success() }}"
    - name: run command
      shell: python
      run: print("** Running python script in post build step!")
      if: "${{ success() }}"
    - uses: actions/setup-node@v2
      if: "${{ success() }}"
    - name: Run Node Command
      shell: node {0}
      run: console.log("Nooodddeee!")
      if: "${{ success() }}"
    - name: run command
      shell: bash
      run: echo "I am a shell build step that runs on cancel!!"
      if: "${{ cancelled() }}"
#     # org.jenkinsci.plugins.postbuildscript.model.PostBuildStep was not transformed because there is no suitable equivalent for a job status of 'NOT_BUILT' in GitHub Actions
#     - name: run command
#       shell: bash
#       run: echo "I don't run because 'NOT _BUILT' is not supported"
#       if: NOT_BUILT
