name: build-playground/WindowsMachineFileCopy
on:
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'true'
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |-
        $sourcePath = "${{ env.SOURCE_PATH }}"
        $robocopyParameters="${{ env.ADDITIONAL_COPY_ARGS }}"
        $isFileCopy = Test-Path -Path $sourcePath -PathType Leaf
        $sourceDirectory = $sourcePath
        $filesToCopy = ""
        if($isFileCopy) {
          $sourceDirectory = Split-Path $sourcePath
          $filesToCopy = Split-Path $sourcePath -Leaf
          if(-not $sourceDirectory){ $sourceDirectory = "." }
        }
        else {
          $robocopyParameters += " /E"
        }
        # mount machine file share
        $psCredentialObject = New-Object pscredential -ArgumentList "${{ env.USER }}", (ConvertTo-SecureString -String "${{ env.PASSWORD }}" -AsPlainText -Force)
        New-PSDrive -Name 'WFCPSDrive' -PSProvider FileSystem -Root "${{ env.DESTINATION }}" -Credential $psCredentialObject -ErrorAction "Stop"
        # clean destination
        if("${{ env.CLEAN_DESTINATION}}" -eq "true") {
          $tempDirectory = "${{ runner.temp }}/clean_up"
          New-Item -ItemType Directory -Force -Path $tempDirectory
          Invoke-Expression "robocopy `"$tempDirectory`" `"${{ env.DESTINATION }}`" `"*.*`" /NOCOPY /E /PURGE"
          Remove-Item $tempDirectory -Recurse -ErrorAction Ignore
        }
        # copy files
        Invoke-Expression "robocopy `"$sourceDirectory`" `"${{ env.DESTINATION }}`" `"$filesToCopy`" $robocopyParameters"
        # robocopy exitcodes of 0 thru 8 are considered successful
        $copyExitCode = ($LASTEXITCODE -ge 8) ? 1 : 0
        # remove file share
        Remove-PSDrive -Name "WFCPSDrive" -ErrorAction SilentlyContinue
        exit $copyExitCode
      env:
        USER: jd
        PASSWORD: "${{ secrets.WIN_SHARE_PASSWORD }}"
        SOURCE_PATH: ".github/workflows/"
        DESTINATION: "\\\\jd-testing.westus.cloudapp.azure.com\\C$\\Users\\jd\\Desktop\\testing"
        ADDITIONAL_COPY_ARGS: "/COPY:DAT"
        CLEAN_DESTINATION: true
