name: build-playground/WindowsMachineFileCopy
on:
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'true'
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |-
        $sourcePath = ".github/workflows"
        $robocopyParameters="/COPY:DAT"
        $isFileCopy = Test-Path -Path $sourcePath -PathType Leaf
        $sourceDirectory = $sourcePath
        $filesToCopy = ""
        if($isFileCopy)
        {
            $sourceDirectory = Split-Path $sourcePath
            $filesToCopy = Split-Path $sourcePath -Leaf
            if(-not $sourceDirectory){ $sourceDirectory = "." }
        }
        if(-not $fileCopy.IsPresent) { $robocopyParameters += " /E" }
        $psCredentialObject = New-Object pscredential -ArgumentList 'jd', (ConvertTo-SecureString -String '${{ secrets.WIN_SHARE_PASSWORD }}' -AsPlainText -Force)
        New-PSDrive -Name 'WFCPSDrive' -PSProvider FileSystem -Root \\52.186.49.95\C$\Users\jd\Desktop\testing -Credential $psCredentialObject -ErrorAction 'Stop'
        robocopy "$sourceDirectory" "\\52.186.49.95\C$\Users\jd\Desktop\testing" "$filesToCopy" $robocopyParameters
        $copyExitCode = ($LASTEXITCODE -ge 8) ? 1 : 0
        net use /delete '\\52.186.49.95\C$\Users\jd\Desktop\testing' '2>NUL'
        exit $copyExitCode
