name: build-playground/WindowsMachineFileCopy
on:
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'true'
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |-
        $sourcePath = ".github/workflows/main.yml"
        $robocopyParameters="/COPY:DAT"
        $isFileCopy = Test-Path -Path $sourcePath -PathType Leaf
        $sourceDirectory = $sourcePath
        $filesToCopy = ""
        if($isFileCopy)
        {
            $sourceDirectory = Split-Path $sourcePath
            $filesToCopy = Split-Path $sourcePath -Leaf
            if(-not $sourceDirectory){ $sourceDirectory = "." }
        }
        if(-not $fileCopy.IsPresent) { $robocopyParameters += " /E" }
        $psCredentialObject = New-Object pscredential -ArgumentList 'jd', (ConvertTo-SecureString -String '${{ secrets.WIN_SHARE_PASSWORD }}' -AsPlainText -Force)
        New-PSDrive -Name 'WFCPSDrive' -PSProvider FileSystem -Root \\52.170.75.125\C$\Users\jd\Desktop\testing -Credential $psCredentialObject -ErrorAction 'Stop'
        $command = "robocopy `"$sourceDirectory`" `"\\52.170.75.125\C$\Users\jd\Desktop\testing`" `"$filesToCopy`" $robocopyParameters"
        Invoke-Expression $command
        $copyExitCode = ($LASTEXITCODE -ge 8) ? 1 : 0
        Remove-PSDrive -Name "WFCPSDrive" -ErrorAction SilentlyContinue\
        Get-PSDrive
        exit $copyExitCode
