name: jdunham-infomagnus/ssh_exec
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.SSH_EXEC_KEY }}"
        name: id_rsa
        known_hosts: "${{ secrets.SSH_EXEC_KNOWN_HOSTS }}"
        if_key_exists: fail
    - name: run script over ssh
      run: |-
        ssh -T ec2-user@3.92.185.186 -p 22 <<'EOL'
        echo "before script"
        EOL
    - name: run command
      shell: python
      run: print("Building something")
    - name: run script over ssh
      run: |-
        ssh -T ec2-user@3.92.185.186 -p 22 <<'EOL'
        echo "after script"
        EOL
