# This is a basic workflow to help you get started with Actions

name: SSH Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: |-
        echo "${{ github.workflow }}-${{ github.run_id }}" > job.txt
        echo "testing" > new.txt
        mkdir -p new/test
        echo "{}" > new/test/bar.json
        ls new/test
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.SSH_KEY }}"
        name: id_rsa-ssh_server
        known_hosts: "${{ secrets.KNOWN_HOSTS }}"
        if_key_exists: fail
        config: |
          Host SSH_SERVER
            HostName ${{ secrets.SSH_HOST_NAME }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/id_rsa-ssh_server
    - id: set-transfer-files
      uses: actions/github-script@v3
      with:
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const globber = await glob.create(#{source_files})
          const dirs = []
#           for await (const file of globber.globGenerator()) {
#               if ((await fs.lstat(file)).isDirectory()) continue
#               if (!dirs.includes(path.dirname(file))) {
#                 dirs.push(path.dirname(file));
#               }
#               console.log(file);
#           }
          console.log("Print Dirs");
          console.log(dirs);
          return dirs.join(" ");
    - name: run SSH_SERVER file transfer
      run: |-
        echo '${{steps.set-transfer-files.outputs.result}}'
        ssh SSH_SERVER 'mkdir -p ${{steps.set-transfer-files.outputs.result}}'
      env:
        REMOTE_DIRECTORY: "./goo"
    - name: run SSH_SERVER commands over ssh
      run: |-
        ssh SSH_SERVER << EOF
           echo "Hi from Jenkins $(date)" > remote_server.txt
           echo "Hello Again!"
        EOF
