name: build-playground/predeploymentApproval
on:
  workflow_dispatch:
jobs:
  Stage-1:
    runs-on: windows-latest
    environment:
      name: Stage-1
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
      - run: echo "Stage-1"
      
  Stage-2:
    needs:
    - Stage-1
    runs-on: windows-latest
    environment:
      # Post deployment approvers were not transformed because there is no suitable equivalent in GitHub Actions
      name: Stage-2
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
      - run: echo "Stage-1"
