name: ssh test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: |-
        echo "${{ github.workflow }}-${{ github.run_id }}" > job.txt
        echo "testing" > new.txt
        echo "fun!" > fun.txt
        mkdir -p new/test
        echo "{}" > new/test/bar.json
        ls new/test
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.SSH_KEY }}"
        name: id_rsa-joels_temp_ssh_server
        known_hosts: "${{ secrets.KNOWN_HOSTS }}"
        if_key_exists: fail
        config: |
          Host JOELS_TEMP_SSH_SERVER
            HostName ${{ secrets.SSH_HOST_NAME }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/id_rsa-joels_temp_ssh_server
    - name: setup file transfer file
      uses: actions/github-script@v3
      with:
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const patterns = "*.txt,new/test/*.json,!fun.txt,!**/*~,!**/#*#,!**/.#*,!**/%*%,!**/._*,!**/CVS,!**/CVS/**,!**/.cvsignore,!**/SCCS,!**/SCCS/**,!**/vssver.scc,!**/.svn,!**/.svn/**,!**/.DS_Store,!**/.git,!**/.git/**,!**/.gitattributes,!**/.gitignore,!**/.gitmodules,!**/.hg,!**/.hg/**,!**/.hgignore,!**/.hgsub,!**/.hgsubstate,!**/.hgtags,!**/.bzr,!**/.bzr/**,!**/.bzrignore"
          const globber = await glob.create(patterns.replace(",", "\n"))
          const files = []
          for await (const file of globber.globGenerator()) {
              if ((await fs.lstat(file)).isDirectory()) continue
              files.push(path.relative(process.cwd(), file))
          }
          fs.writeFile("joels_temp_ssh_server-transfer.txt", files.join("\n"), (err) => {})
    - name: run file transfers
      run: |-
        ssh JOELS_TEMP_SSH_SERVER 'mkdir -p goo/foo'
        tar -cvf joels_temp_ssh_server-transfer.tar --files-from joels_temp_ssh_server-transfer.txt
        scp joels_temp_ssh_server-transfer.tar JOELS_TEMP_SSH_SERVER:
        ssh JOELS_TEMP_SSH_SERVER 'tar -xvf joels_temp_ssh_server-transfer.tar -C goo/foo && rm joels_temp_ssh_server-transfer.tar'
    - name: run commands over ssh
      run: |-
        ssh JOELS_TEMP_SSH_SERVER 'echo "Hi from Jenkins $(date)" > remote_server.txt'
        ssh JOELS_TEMP_SSH_SERVER 'echo "Hello Again!"'
