name: test temp
on:
  workflow_dispatch:
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: mkdir testing
    - name: Create Inline SQL File
      shell: bash
      run: |-
        cat > testing//dacpac_deploy.sql <<'EOL'
        INSERT INTO dbo.BuildVersion ([Database Version], VersionDate) VALUES (1, CURRENT_TIMESTAMP)
        INSERT INTO dbo.BuildVersion ([Database Version], VersionDate) VALUES (1, CURRENT_TIMESTAMP)
        EOL
    - run: ls .
    - run: ls testing
    - run: cat testing\dacpac_deploy.sql
