name: test_docker_build_push
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker Image
      run: docker build '.' -t dunhamj/hello-world:latest
    - name: Push Docker Image
      run: docker push dunhamj/hello-world:latest
    - name: Logout of Docker Hub
      run: docker logout
