name: test temp
on:
  workflow_dispatch:
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - shell: bash
      run: echo ${{ runner.temp }}
    - shell: bash
      run: |-
        pwd
        ls  /d/a/_temp
