name: test temp
on:
  workflow_dispatch:
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Create Inline SQL File
      shell: bash
      run: |-
        cat > ${{ runner.temp }}\dacpac_deploy.sql <<'EOL'
        INSERT INTO dbo.BuildVersion ([Database Version], VersionDate) VALUES (1, CURRENT_TIMESTAMP)
        INSERT INTO dbo.BuildVersion ([Database Version], VersionDate) VALUES (1, CURRENT_TIMESTAMP)
        EOL
    - run: ls ${{ runner.temp }}
    - run: cat ${{ runner.temp }}/dacpac_deploy.sql
