name: jdunham-infomagnus/throttle_designer
on:
  workflow_dispatch:
concurrency:
  # Note: 'concurrency' may not be supported on enterprise versions
  group: "${{ github.workflow }}"
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
