# This is a basic workflow to help you get started with Actions

name: xcode-select
on: workflow_dispatch

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: xcodebuild -version
        
      - name: Run a multi-line script
        run: |
          xcode-select -s /Applications/Xcode_11.7.app
          xcodebuild -version
          xcode-select -s /Applications/Xcode_13.0.app
          xcodebuild -version
